fix: suggest to use docker compose v2

diff --git a/gdrcd-stack b/gdrcd-stack
--- a/gdrcd-stack
+++ b/gdrcd-stack
@@ -57,6 +57,21 @@ _checkDocker() {
   fi;
 }
 
+# Check if docker compose is installed
+_checkDockerCompose() {
+  if ! type "docker-compose" >/dev/null 2>&1; then
+    echo "Error: this stack requires Docker Compose v2, please install it and try again"
+    exit 1;
+  fi;
+
+
+  # check if docker compose is installed
+  if ! type "docker compose" >/dev/null 2>&1; then
+    echo "Error: Docker Compose not found"
+    exit 1;
+  fi;
+}
+
 # Check if environment is set
 _checkEnvironment() {
   if [[ -z ${ENV+x} ]]; then
@@ -110,6 +125,7 @@ restart() {
 # !IMPORTANT
 # Execute the action passed as the first argument
 _checkDocker; \
+_checkDockerCompose; \
 _checkEnvironment; \
 _isCommand "${1:-help}"; \
 # This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
